services:
  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: #WRITE your image name
    container_name: #WRITE your container name
    ports:
      - #"3000:3000" #WRITE your port
    environment:
      DB_HOST:
      DB_PORT:
      DB_USERNAME:
      DB_PASSWORD:
      DB_NAME:
      PORT:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-qO-", "Write your api link"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14-alpine
    container_name:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: 
    ports:
      - "5432:5432" #Write your port mapping here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
